"""English: the Old English elements behind most of England's place names.

Head-last compounds run together — Ash-ford, Wolver-ton, Chester-field — with a founder
joined by -ing- or a genitive -s (Birmingham, Beorma's people's home). The rivers are the
older British names the English kept: Avon, Ouse, Tame. Set `naming_substrate_pack:
welsh` and the whole map works that way, English towns on Brittonic rivers.
"""

from .base import Pack

PACK = Pack(
    key="english",
    name="English",
    heads={
        "ford": ("ford",),
        "bridge": ("bridge", "brigg"),
        "confluence": ("meet", "water"),
        "mouth": ("mouth",),
        "falls": ("force", "weir", "fall"),
        "pass": ("gate", "yate", "hope"),
        "harbour": ("haven", "hithe", "port"),
        "shore": ("strand", "ore", "sea"),
        "market": ("market", "cheap"),
        "mine": ("pit", "delph", "mine"),
        "clearing": ("ley", "leigh", "ly"),
        "spring": ("well", "wells", "font"),
        "hill": ("don", "hill", "hoe", "low"),
        "steading": ("ton", "ham", "stead"),
        "hamlet": ("thorpe", "stead"),
        "enclosure": ("worth", "hay", "fold"),
        "cottages": ("cote", "cot", "cott"),
        "field": ("field", "feld"),
        "town": ("ton", "ham", "ington"),
        "wick": ("wick", "wich"),
        "stow": ("stow", "stowe"),
        "burgh": ("bury", "borough", "burgh"),
        "hall": ("hall", "sall"),
        "wall": ("chester", "cester", "caster"),
    },
    quals={
        "marsh": ("mars", "more"),
        "fen": ("fen", "fenn"),
        "deepwood": ("holt", "dern"),
        "wood": ("wood", "wod"),
        "thorn": ("thorn", "thorne"),
        "meadow": ("mead", "made"),
        "cold": ("cold", "cald"),
        "sand": ("sand", "sond"),
        "stone": ("stan", "stone"),
        "salt": ("salt", "sal"),
        "rich": ("good", "fat"),
        "high": ("high", "heigh"),
        "oak": ("ack", "oak", "ac"),
        "ash": ("ash", "esh"),
        "elm": ("elm", "em"),
        "birch": ("birch", "berk"),
        "pine": ("fir", "pine"),
        "palm": ("palm",),
        "broom": ("brom", "broom"),
        "reed": ("reed", "rede"),
        "ox": ("ox", "oxen"),
        "deer": ("hart", "der"),
        "swine": ("swin", "swine"),
        "horse": ("hors", "stud"),
        "hare": ("har", "hare"),
        "elk": ("elk", "elch"),
        "wolf": ("wolf", "wol"),
        "bear": ("ber", "bear"),
        "goat": ("gat", "goat"),
        "crane": ("cran", "cram"),
        "eagle": ("earn", "arn"),
        "white": ("whit", "white"),
        "black": ("black", "blake"),
        "red": ("red", "rud"),
        "green": ("green", "grin"),
        "north": ("nor", "north"),
        "south": ("sut", "sud", "south"),
        "east": ("eas", "east"),
        "west": ("wes", "west"),
        "great": ("much", "great", "mickle"),
        "little": ("little", "lit"),
    },
    compound=("{q}{h}",),
    founder=("{p}ing{h}", "{p}s{h}", "{p}{h}"),
    river_on=("{r}{h}", "{r}{h}", "{h}-on-{r}", "{h}-upon-{r}"),
    person_first=(
        "Athel",
        "Ed",
        "Wulf",
        "Bern",
        "Os",
        "Sige",
        "Kin",
        "Leof",
        "God",
        "Bright",
        "Alf",
        "Here",
        "Wig",
        "Cuth",
        "Dun",
    ),
    person_second=("ric", "wulf", "win", "stan", "mund", "ward", "helm", "gar", "red", "noth"),
    river_roots=(
        "Aln",
        "Ouse",
        "Tame",
        "Leam",
        "Wey",
        "Wear",
        "Cole",
        "Rother",
        "Brent",
        "Lune",
        "Idle",
        "Mole",
        "Stour",
        "Ure",
        "Nidd",
        "Swale",
        "Kennet",
        "Loddon",
        "Colne",
        "Dart",
        "Otter",
        "Tavy",
        "Camel",
        "Aire",
        "Calder",
        "Dove",
        "Frome",
        "Test",
        "Itchen",
        "Arun",
    ),
    river_patterns=("{root}", "{root}", "little {root}", "{root}brook"),
    # A bare English head is a bound form — nobody lives in "Ton" — so a bare name takes
    # the commonest free-standing prefixes: Upton, Netherton.
    bare=("up{h}", "nether{h}"),
    particles=frozenset({"on", "upon"}),
)
