"""French: the medieval French of northern France and Normandy.

The head leads and the qualifier follows, joined by hyphens and particles:
Gué-du-Chêne, Pont-l'Évêque, Fontaine-Blanche. A founder usually comes first and runs
into the head, as the Norman -ville names do (Hérouville, Herulf's estate). The old words
survive where the modern ones would not: plessis for an enclosure, essart for a clearing,
condé for a confluence.
"""

from .base import Pack

PACK = Pack(
    key="french",
    name="French",
    heads={
        "ford": ("gué",),
        "bridge": ("pont",),
        "confluence": ("condé", "confluent"),
        "mouth": ("havre", "bouche"),
        "falls": ("saut", "chute"),
        "pass": ("col", "pas", "port"),
        "harbour": ("port", "havre"),
        "shore": ("rive", "grève"),
        "market": ("marché", "foire"),
        "mine": ("minière", "forge"),
        "clearing": ("essart", "sart"),
        "spring": ("fontaine", "font"),
        "hill": ("mont", "butte", "puy"),
        "steading": ("ville", "mas", "court"),
        "hamlet": ("hameau", "mesnil", "ménil"),
        "enclosure": ("clos", "plessis"),
        "cottages": ("bordes", "loges"),
        "field": ("champ", "champs"),
        "town": ("ville", "bourg"),
        "wick": ("bastide", "bourg"),
        "stow": ("carrefour",),
        "burgh": ("château", "fort"),
        "hall": ("salle",),
        "wall": ("châtel", "castel"),
    },
    quals={
        "marsh": ("du-marais", "des-marais"),
        "fen": ("des-mares", "de-la-fagne"),
        "deepwood": ("en-forêt", "de-la-forêt"),
        "wood": ("du-bois", "des-bois"),
        "thorn": ("l'épine", "des-épines"),
        "meadow": ("des-prés", "du-pré"),
        "cold": ("froid", "froide"),
        "sand": ("des-sables", "du-sable"),
        "stone": ("des-pierres", "la-roche"),
        "salt": ("du-sel", "des-salines"),
        "rich": ("riche", "le-bon"),
        "high": ("haut", "le-haut"),
        "oak": ("du-chêne", "aux-chênes"),
        "ash": ("du-fresne", "des-frênes"),
        "elm": ("l'orme", "des-ormes"),
        "birch": ("du-boulay", "des-bouleaux"),
        "pine": ("des-pins", "la-pinède"),
        "palm": ("des-palmiers",),
        "broom": ("du-genêt", "des-genêts"),
        "reed": ("des-roseaux",),
        "ox": ("aux-bœufs", "du-bœuf"),
        "deer": ("du-cerf", "aux-cerfs"),
        "swine": ("aux-porcs", "du-porc"),
        "horse": ("aux-chevaux", "du-cheval"),
        "hare": ("du-lièvre",),
        "elk": ("de-l'élan",),
        "wolf": ("du-loup", "aux-loups"),
        "bear": ("de-l'ours", "aux-ours"),
        "goat": ("aux-chèvres", "de-la-chèvre"),
        "crane": ("aux-grues",),
        "eagle": ("de-l'aigle",),
        "white": ("blanc", "blanche"),
        "black": ("noir", "noire"),
        "red": ("rouge",),
        "green": ("vert", "verte"),
        "north": ("du-nord",),
        "south": ("du-midi",),
        "east": ("de-l'est",),
        "west": ("de-l'ouest",),
        "great": ("le-grand", "grand"),
        "little": ("le-petit", "petit"),
    },
    compound=("{h}-{q}",),
    founder=("{p}{h}", "{h}-{p}"),
    river_on=("{h}-sur-{r}", "{h}-sur-{r}", "{h}-lès-{r}"),
    person_first=(
        "Roger",
        "Raoul",
        "Gautier",
        "Hugues",
        "Guillaume",
        "Robert",
        "Richard",
        "Baudouin",
        "Thibaut",
        "Renaud",
        "Aubert",
        "Girard",
        "Herbert",
        "Anseau",
        "Garnier",
    ),
    river_roots=(
        "Loire",
        "Seine",
        "Marne",
        "Oise",
        "Aisne",
        "Somme",
        "Orne",
        "Vire",
        "Risle",
        "Eure",
        "Loir",
        "Cher",
        "Indre",
        "Vienne",
        "Creuse",
        "Lot",
        "Tarn",
        "Aude",
        "Isle",
        "Sèvre",
        "Vilaine",
        "Rance",
        "Meuse",
        "Sarthe",
        "Mayenne",
        "Yonne",
        "Aube",
        "Dives",
        "Touques",
    ),
    river_patterns=("{root}", "{root}", "petite-{root}", "grande-{root}"),
    particles=frozenset({"de", "du", "des", "la", "le", "les", "aux", "en", "sur", "sous", "lès"}),
)
