"""Hobbitish: the homely English of Tolkien's Shire.

Tolkien anglicised the Shire's Westron into rural English with a comic turn, and this
pack does the same: a mine is a delving, a big thing is michel, a meeting-place a moot,
a hole a smial, a marsh a marish. Names are compounds read as English (Overhill,
Longbottom, Michel Delving), sometimes two words. Founders have the short, jolly names
of hobbit families, and rivers the sort a hobbit would give them — Willowwater,
Thistlebrook.
"""

from .base import Pack

PACK = Pack(
    key="hobbitish",
    name="Hobbitish",
    heads={
        "ford": ("ford",),
        "bridge": ("bridge",),
        "confluence": ("meet",),
        "mouth": ("mouth",),
        "falls": ("fall", "weir"),
        "pass": ("gap", "cutting"),
        "harbour": ("haven", "wharf"),
        "shore": ("side", "bank"),
        "market": ("market", "fair"),
        "mine": ("delving", "pits"),
        "clearing": ("stock", "ley"),
        "spring": ("well", "spring"),
        "hill": ("hill", "barrow", "knoll"),
        "steading": ("ton", "by", "bottom"),
        "hamlet": ("end", "row"),
        "enclosure": ("fold", "hay", "garth"),
        "cottages": ("smials", "holes"),
        "field": ("field", "furrows", "acre"),
        "town": ("ton", "by", "borough"),
        "wick": ("wich", "market"),
        "stow": ("moot",),
        "burgh": ("borough", "bury"),
        "hall": ("hall",),
        "wall": ("hedge", "wall"),
    },
    quals={
        "marsh": ("marish", "marsh"),
        "fen": ("fen", "bog"),
        "deepwood": ("deep", "old"),
        "wood": ("wood", "woody"),
        "thorn": ("thorn", "bramble"),
        "meadow": ("green", "mead"),
        "cold": ("cold",),
        "sand": ("sand",),
        "stone": ("stone",),
        "salt": ("salt",),
        "rich": ("fair", "good"),
        "high": ("over", "high"),
        "oak": ("oak",),
        "ash": ("ash",),
        "elm": ("elm",),
        "birch": ("birch",),
        "pine": ("pine",),
        "palm": ("palm",),
        "broom": ("broom", "gorse"),
        "reed": ("rush", "reed"),
        "ox": ("ox", "bull"),
        "deer": ("hart",),
        "swine": ("hog", "pig"),
        "horse": ("pony", "nag"),
        "hare": ("hare", "rabbit", "coney"),
        "elk": ("elk",),
        "wolf": ("wolf",),
        "bear": ("bear",),
        "goat": ("goat",),
        "crane": ("heron",),
        "eagle": ("eagle",),
        "white": ("white", "whit"),
        "black": ("black",),
        "red": ("red",),
        "green": ("green",),
        "north": ("north", "nor"),
        "south": ("south", "sud"),
        "east": ("east",),
        "west": ("west",),
        "great": ("long", "great", "michel"),
        "little": ("little", "nob"),
    },
    compound=("{q}{h}", "{q}{h}", "{q} {h}"),
    founder=("{p}s {h}", "{p}{h}"),
    river_on=("{r}{h}", "{h} on {r}"),
    person_first=(
        "Bil",
        "Fol",
        "Hob",
        "Tom",
        "Mil",
        "Pod",
        "Dud",
        "Ros",
        "Bun",
        "Lob",
        "Wil",
        "Hal",
    ),
    person_second=("bo", "co", "do", "go", "mo", "bert", "wise", "kin"),
    river_roots=(
        "shir",
        "bay",
        "wither",
        "whit",
        "mill",
        "rush",
        "reed",
        "sally",
        "otter",
        "cress",
        "willow",
        "thistle",
        "bramble",
        "hay",
        "barley",
        "hazel",
    ),
    river_patterns=("{root}water", "{root}brook", "{root}bourne", "{root}wine"),
    bare=("{h}", "over{h}", "under{h}"),
    particles=frozenset({"on"}),
)
