"""Norse: the Old Norse of Scandinavia and the Danelaw.

-by and -thorp for a farm and its outlier, -thwaite and -rud for a clearing, -vik for a
bay, -foss for a waterfall, -ting for the place the assembly met (Tingwall, Dingwall). A
founder takes a genitive -s: Grimsby is Grímr's farm.
"""

from .base import Pack

PACK = Pack(
    key="norse",
    name="Norse",
    heads={
        "ford": ("vad", "wath"),
        "bridge": ("bro", "brygga"),
        "confluence": ("mot", "møte"),
        "mouth": ("os", "mynne"),
        "falls": ("foss", "fors"),
        "pass": ("skard", "gil"),
        "harbour": ("havn", "hamn"),
        "shore": ("strand", "nes"),
        "market": ("köping", "kaupang"),
        "mine": ("gruva", "hytta"),
        "clearing": ("thwaite", "rud", "ryd"),
        "spring": ("kelda", "kilde"),
        "hill": ("haug", "berg", "how"),
        "steading": ("by", "stad", "bø"),
        "hamlet": ("thorp", "torp"),
        "enclosure": ("gard", "garth"),
        "cottages": ("seter", "scale"),
        "field": ("vang", "völl"),
        "town": ("by", "stad"),
        "wick": ("vik", "kaupang"),
        "stow": ("ting", "thing"),
        "burgh": ("borg", "hus"),
        "hall": ("sal", "hall"),
        "wall": ("virki", "borg"),
    },
    quals={
        "marsh": ("myr", "mos"),
        "fen": ("kjær", "fen"),
        "deepwood": ("mörk", "myrk"),
        "wood": ("skog", "lund", "vid"),
        "thorn": ("torn", "thorn"),
        "meadow": ("eng",),
        "cold": ("kald",),
        "sand": ("sand",),
        "stone": ("sten", "stein"),
        "salt": ("salt",),
        "rich": ("god", "rik"),
        "high": ("hög", "hå"),
        "oak": ("ek", "eik"),
        "ash": ("ask",),
        "elm": ("alm",),
        "birch": ("björk", "bjark"),
        "pine": ("fur", "tall"),
        "palm": ("palm",),
        "broom": ("lyng", "ljung"),
        "reed": ("ror", "sev"),
        "ox": ("oxa", "naut"),
        "deer": ("hjort", "dyr"),
        "swine": ("svin", "gris"),
        "horse": ("hest", "ross"),
        "hare": ("hare", "hera"),
        "elk": ("elg", "älg"),
        "wolf": ("ulv", "ulf"),
        "bear": ("björn", "bjarn"),
        "goat": ("geit", "get"),
        "crane": ("trane", "trana"),
        "eagle": ("örn", "arn"),
        "white": ("hvit", "vit"),
        "black": ("svart", "svar"),
        "red": ("röd", "raud"),
        "green": ("grön", "grøn"),
        "north": ("nor", "nord"),
        "south": ("sud", "sør"),
        "east": ("aust", "ös"),
        "west": ("vest",),
        "great": ("stor", "mikla"),
        "little": ("lill", "litla"),
    },
    compound=("{q}{h}",),
    founder=("{p}s{h}", "{p}{h}"),
    river_on=("{r}{h}",),
    person_first=(
        "Thor",
        "As",
        "Gunn",
        "Arn",
        "Ulf",
        "Sig",
        "Ing",
        "Hall",
        "Svein",
        "Grim",
        "Orm",
        "Kol",
        "Rag",
        "Stein",
        "Bjorn",
    ),
    person_second=("", "kel", "stein", "bjorn", "ulf", "vald", "geir", "mund"),
    river_roots=(
        "Glomma",
        "Lågen",
        "Otra",
        "Driva",
        "Rauma",
        "Namsen",
        "Orkla",
        "Gaula",
        "Vefsna",
        "Klara",
        "Ljusna",
        "Indal",
        "Rane",
        "Lule",
        "Pite",
        "Tana",
        "Alta",
        "Eira",
        "Aura",
        "Sira",
        "Nid",
        "Ätran",
        "Nissan",
        "Lagan",
        "Viskan",
        "Dal",
        "Umea",
        "Kalix",
    ),
    river_patterns=("{root}", "{root}", "lilla {root}", "stora {root}"),
    bare=("{h}", "ny{h}"),
)
