"""Spanish: Castilian place names of the Reconquista and after.

The head leads. An adjective follows it and agrees — Fuente Blanca, Puerto Alto — or
runs into it as one word (Villablanca, Fuentefría); a noun follows with de and the
article: Fuente de los Robles, Vado del Lobo. A town on a river takes de, as Aranda de
Duero does, and a founder de too (Villa de Don Fadrique).

Puerto is both a harbour and a mountain pass in Spain, and both are used. The rozas of
Las Rozas are clearings, and a castro is a walled hill-fort (Castrojeriz).
"""

from .base import Pack

PACK = Pack(
    key="spanish",
    name="Spanish",
    heads={
        "ford": ("vado",),
        "bridge": ("puente",),
        "confluence": ("juntas",),
        "mouth": ("boca",),
        "falls": ("salto", "cascada"),
        "pass": ("puerto", "paso"),
        "harbour": ("puerto",),
        "shore": ("playa", "orilla"),
        "market": ("mercado", "feria"),
        "mine": ("mina", "minas"),
        "clearing": ("rozas",),
        "spring": ("fuente", "fontana"),
        "hill": ("cerro", "monte", "peña", "alto"),
        "steading": ("cortijo", "granja", "alquería"),
        "hamlet": ("aldea", "caserío"),
        "enclosure": ("corral", "cercado"),
        "cottages": ("casas", "chozas"),
        "field": ("campo", "llano"),
        "town": ("villa", "puebla"),
        "wick": ("feria", "mercadal"),
        "stow": ("concejo",),
        "burgh": ("castillo", "alcázar"),
        "hall": ("palacio",),
        "wall": ("castro",),
    },
    genders={
        "vado": "m",
        "puente": "m",
        "juntas": "fp",
        "boca": "f",
        "salto": "m",
        "cascada": "f",
        "puerto": "m",
        "paso": "m",
        "playa": "f",
        "orilla": "f",
        "mercado": "m",
        "feria": "f",
        "mina": "f",
        "minas": "fp",
        "rozas": "fp",
        "fuente": "f",
        "fontana": "f",
        "cerro": "m",
        "monte": "m",
        "peña": "f",
        "alto": "m",
        "cortijo": "m",
        "granja": "f",
        "alquería": "f",
        "aldea": "f",
        "caserío": "m",
        "corral": "m",
        "cercado": "m",
        "casas": "fp",
        "chozas": "fp",
        "campo": "m",
        "llano": "m",
        "villa": "f",
        "puebla": "f",
        "mercadal": "m",
        "concejo": "m",
        "castillo": "m",
        "alcázar": "m",
        "palacio": "m",
        "castro": "m",
    },
    endings={"m": "o", "f": "a", "mp": "os", "fp": "as"},
    quals={
        "marsh": ("de la marisma", "del pantano"),
        "fen": ("de la ciénaga",),
        "deepwood": ("de la selva",),
        "wood": ("del bosque", "del soto"),
        "thorn": ("del espino", "de los espinos"),
        "meadow": ("del prado", "de los prados"),
        "cold": ("frí~",),
        "sand": ("de la arena", "de los arenales"),
        "stone": ("de la piedra", "de las peñas"),
        "salt": ("de la sal", "de las salinas"),
        "rich": ("ric~",),
        "high": ("alt~",),
        "oak": ("del roble", "de la encina"),
        "ash": ("del fresno",),
        "elm": ("del olmo", "de los olmos"),
        "birch": ("del abedul",),
        "pine": ("del pino", "de los pinos"),
        "palm": ("de las palmas",),
        "broom": ("de la retama",),
        "reed": ("de los juncos",),
        "ox": ("de los bueyes",),
        "deer": ("del ciervo",),
        "swine": ("de los puercos",),
        "horse": ("de los caballos",),
        "hare": ("de la liebre",),
        "elk": ("del alce",),
        "wolf": ("del lobo", "de los lobos"),
        "bear": ("del oso",),
        "goat": ("de las cabras",),
        "crane": ("de las grullas",),
        "eagle": ("del águila",),
        "white": ("blanc~",),
        "black": ("negr~",),
        "red": ("roj~", "bermej~"),
        "green": ("verde",),
        "north": ("del norte",),
        "south": ("del sur",),
        "east": ("de levante",),
        "west": ("de poniente",),
        "great": ("mayor",),
        "little": ("chic~", "menor"),
    },
    compound=("{h} {q}",),
    adjective=("{h} {a}", "{h} {a}", "{h}{a}"),
    founder=("{h} de {p}", "{h} de don {p}"),
    river_on=("{h} de {r}",),
    person_first=(
        "Rodrigo",
        "Fernando",
        "Sancho",
        "Alfonso",
        "Gonzalo",
        "Nuño",
        "Pelayo",
        "Ramiro",
        "Diego",
        "Martín",
        "Álvaro",
        "Fadrique",
        "Gutierre",
        "Bermudo",
        "Ordoño",
    ),
    river_roots=(
        "Duero",
        "Tajo",
        "Ebro",
        "Júcar",
        "Segura",
        "Guadiana",
        "Miño",
        "Sil",
        "Esla",
        "Pisuerga",
        "Jarama",
        "Henares",
        "Tormes",
        "Alberche",
        "Genil",
        "Turia",
        "Cinca",
        "Segre",
        "Jalón",
        "Arlanza",
        "Órbigo",
        "Zújar",
        "Tiétar",
        "Huerva",
        "Bidasoa",
        "Nalón",
        "Adaja",
        "Eresma",
        "Duratón",
        "Guadalete",
    ),
    river_patterns=("{root}", "{root}", "arroyo {root}", "{root} chico"),
    particles=frozenset({"de", "del", "la", "las", "los", "el", "don"}),
)
