"""Welsh: Brittonic place names, head first.

The head leads — Aber-ystwyth, the mouth of the Ystwyth; Pont-y-pridd, the bridge of the
earth; Llan-deilo, Teilo's church-enclosure — which is the opposite order to English and
is what makes a Welsh map read as Welsh at a glance. The river roots are the old British
river names, which makes this the natural substrate under English or Norse towns.

Mutation is written in where the common forms carry it (ddu, fawr, gwyn after a
feminine head) rather than modelled.
"""

from .base import Pack

PACK = Pack(
    key="welsh",
    name="Welsh",
    heads={
        "ford": ("rhyd",),
        "bridge": ("pont",),
        "confluence": ("cymer",),
        "mouth": ("aber",),
        "falls": ("rhaeadr", "pistyll"),
        "pass": ("bwlch",),
        "harbour": ("porth",),
        "shore": ("traeth", "glan"),
        "market": ("ffair", "marchnad"),
        "mine": ("gwaith", "cloddfa"),
        "clearing": ("llannerch",),
        "spring": ("ffynnon",),
        "hill": ("bryn", "moel", "pen", "crug"),
        "steading": ("tre", "tref", "bod"),
        "hamlet": ("pentre", "bod"),
        "enclosure": ("cae", "llan"),
        "cottages": ("hafod", "lluest"),
        "field": ("maes", "cae"),
        "town": ("tre", "tref"),
        "wick": ("ffair", "tre"),
        "stow": ("llys",),
        "burgh": ("caer", "dinas"),
        "hall": ("neuadd", "llys"),
        "wall": ("caer",),
    },
    quals={
        "marsh": ("cors", "gors"),
        "fen": ("gwern", "mign"),
        "deepwood": ("fforest", "celli"),
        "wood": ("coed", "goed", "gelli"),
        "thorn": ("draen", "ddrain"),
        "meadow": ("dôl", "ddôl"),
        "cold": ("oer",),
        "sand": ("tywyn", "tywod"),
        "stone": ("maen", "faen", "garreg"),
        "salt": ("halen",),
        "rich": ("fras",),
        "high": ("uchaf",),
        "oak": ("derw", "dderw"),
        "ash": ("onn", "onnen"),
        "elm": ("llwyf",),
        "birch": ("fedw", "bedw"),
        "pine": ("pinwydd",),
        "palm": ("palmwydd",),
        "broom": ("banadl", "eithin"),
        "reed": ("cawn", "hesg"),
        "ox": ("ych",),
        "deer": ("carw", "garw"),
        "swine": ("moch", "hwch"),
        "horse": ("march", "meirch"),
        "hare": ("ysgyfarnog",),
        "elk": ("elc",),
        "wolf": ("blaidd",),
        "bear": ("arth",),
        "goat": ("gafr", "geifr"),
        "crane": ("garan",),
        "eagle": ("eryr",),
        "white": ("gwyn", "wen"),
        "black": ("du", "ddu"),
        "red": ("goch", "coch"),
        "green": ("werdd", "gwyrdd"),
        "north": ("gogledd",),
        "south": ("de",),
        "east": ("dwyrain",),
        "west": ("gorllewin",),
        "great": ("fawr", "mawr"),
        "little": ("fach", "bach"),
    },
    compound=("{h}{q}", "{h}{q}", "{h}-y-{q}"),
    founder=("{h}{p}", "{h} {p}"),
    river_on=("{h}{r}", "{h} {r}"),
    person_first=(
        "Rhodri",
        "Cadog",
        "Tysilio",
        "Dewi",
        "Teilo",
        "Gwynn",
        "Idris",
        "Maelgwn",
        "Cadwgan",
        "Iorwerth",
        "Owain",
        "Hywel",
        "Madog",
        "Einion",
        "Meurig",
    ),
    river_roots=(
        "Taf",
        "Tywi",
        "Teifi",
        "Conwy",
        "Clwyd",
        "Dyfi",
        "Dwyfor",
        "Ogwr",
        "Nedd",
        "Tawe",
        "Llwchwr",
        "Wysg",
        "Gwy",
        "Hafren",
        "Elai",
        "Rhymni",
        "Cynon",
        "Aeron",
        "Ystwyth",
        "Rheidol",
        "Mawddach",
        "Dysynni",
        "Glaslyn",
        "Alaw",
        "Cefni",
        "Dulas",
        "Ithon",
    ),
    river_patterns=("{root}", "{root}", "{root} fawr", "{root} fach", "nant {root}"),
    particles=frozenset({"y", "yr"}),
)
