"""Generate the hex-math conformance fixture the TypeScript port is checked against.

`campaign/shared/src/hex.ts` is a hand port of `worldgen/core/hex_grid.py`. Ported code
drifts, and hex math drifts silently: a wrong neighbour ordering or a rounding difference
at a hex boundary produces plausible output that is subtly wrong everywhere downstream.

So the Python computes a few hundred cases here, they are committed, and both suites
assert against the same file — `tests/test_hex_conformance.py` on this side and
`campaign/shared/test/hex.conformance.test.ts` on the other. If either implementation
changes behaviour, one of the two goes red.

Regenerate with:

    python3 scripts/gen_hex_fixture.py

and commit the result. A diff here is a deliberate change to the hex model, never noise.
"""

import sys
from pathlib import Path

# Put the repository root ahead of anything else on the path.
#
# `python scripts/foo.py` sets sys.path[0] to `scripts/`, not to the repo root, so an
# editable install of `worldgen` elsewhere on the machine wins the import — which in a
# git worktree means this script silently runs against the *main* checkout's code while
# the tests run against the worktree's. That divergence is invisible until output stops
# matching what the tests say it should.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import json
from pathlib import Path

from worldgen.core.hex import Hex
from worldgen.core.hex_grid import (
    astar,
    axial_to_offset,
    axial_to_pixel,
    distance,
    hex_range,
    neighbors,
    offset_to_axial,
    pixel_to_axial,
    ring,
    round_axial,
)

FIXTURE = (
    Path(__file__).resolve().parent.parent
    / "campaign"
    / "shared"
    / "test"
    / "fixtures"
    / "hex-conformance.json"
)

# Deliberately spread across the origin and both negative axes: axial maths is riddled
# with floor-versus-truncate and sign bugs that only show for negative coordinates, and
# the odd-q offset conversion in particular differs on odd and even columns.
# These are coordinate tables. One pair per line makes them unreadable, so the formatter
# is held off across all three.
# fmt: off
COORDS = [
    (0, 0), (1, 0), (0, 1), (-1, 0), (0, -1), (1, -1), (-1, 1),
    (3, 4), (-3, 4), (3, -4), (-3, -4), (7, 0), (0, 7), (-7, 0), (0, -7),
    (5, 5), (-5, -5), (12, -8), (-12, 8), (63, 63), (1, 2), (2, 1),
]

PAIRS = [(a, b) for a in COORDS[:10] for b in COORDS[:10]]

# Fractional inputs for the rounding path. The exact .5 cases are the point: Python's
# round() is half-to-even and JavaScript's Math.round is half-up, so a naive port puts
# a point on a hex boundary in a different hex.
FRACTIONS = [
    (0.0, 0.0), (0.5, 0.5), (-0.5, -0.5), (0.5, -0.5), (-0.5, 0.5),
    (1.5, 2.5), (-1.5, -2.5), (2.5, -1.5), (0.4, 0.4), (0.6, 0.6),
    (1.2, -3.7), (-4.3, 2.8), (0.3333, 0.6667), (-0.3333, -0.6667),
    (10.5, -5.5), (2.49999, 2.50001),
]

PIXELS = [
    (0.0, 0.0), (30.0, 17.32), (-30.0, -17.32), (15.0, 25.98),
    (45.5, -12.25), (100.0, 100.0), (-100.0, 100.0), (7.5, 3.75),
]
# fmt: on

HEX_SIZE = 20.0

# A synthetic grid for the pathfinding case. The cost formula is arbitrary but must be
# reproduced exactly on the other side; anything with a modulus exercises the frontier's
# tie-breaking, which is what actually decides whether two implementations agree.
ASTAR_W = ASTAR_H = 9


def astar_cost(q: int, r: int) -> float:
    """Node entry cost. A band of impassable hexes forces the search around an obstacle."""
    if q == 4 and r in (0, 1, 2, 3, 4, 5, 6):
        return float("inf")
    return 1.0 + ((q * 7 + r * 13) % 5)


def build() -> dict:
    astar_grid = {
        (q, r): Hex(coord=(q, r), elevation=astar_cost(q, r))
        for q in range(ASTAR_W)
        for r in range(ASTAR_H)
    }
    path = astar(astar_grid, (0, 0), (8, 8), lambda h: h.elevation)

    return {
        "_comment": (
            "Generated by scripts/gen_hex_fixture.py. Do not hand-edit. "
            "Asserted by tests/test_hex_conformance.py and "
            "campaign/shared/test/hex.conformance.test.ts."
        ),
        "hexSize": HEX_SIZE,
        "astar": {
            "width": ASTAR_W,
            "height": ASTAR_H,
            "blockedColumn": 4,
            "blockedRows": [0, 1, 2, 3, 4, 5, 6],
            "start": [0, 0],
            "goal": [8, 8],
            "path": [list(c) for c in path] if path else None,
        },
        "neighbors": [
            {"coord": list(c), "result": [list(n) for n in neighbors(c)]} for c in COORDS
        ],
        "distance": [{"a": list(a), "b": list(b), "result": distance(a, b)} for a, b in PAIRS],
        "ring": [
            {"center": list(c), "radius": rad, "result": [list(h) for h in ring(c, rad)]}
            for c in COORDS[:6]
            for rad in (0, 1, 2, 3, 5)
        ],
        "hexRange": [
            {
                "center": list(c),
                "radius": rad,
                "result": [list(h) for h in hex_range(c, rad)],
            }
            for c in COORDS[:6]
            for rad in (0, 1, 2, 4)
        ],
        "axialToPixel": [
            {"coord": list(c), "result": list(axial_to_pixel(c, HEX_SIZE))} for c in COORDS
        ],
        "pixelToAxial": [
            {
                "x": x,
                "y": y,
                "result": list(pixel_to_axial(x, y, HEX_SIZE)),
            }
            for x, y in PIXELS
        ],
        "roundAxial": [{"q": q, "r": r, "result": list(round_axial((q, r)))} for q, r in FRACTIONS],
        "offsetToAxial": [
            {"col": col, "row": row, "result": list(offset_to_axial(col, row))}
            for col in (-5, -2, -1, 0, 1, 2, 3, 8, 9)
            for row in (-3, 0, 1, 4, 7)
        ],
        "axialToOffset": [{"coord": list(c), "result": list(axial_to_offset(c))} for c in COORDS],
    }


def main() -> None:
    FIXTURE.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE.write_text(json.dumps(build(), indent=2) + "\n")
    print(f"wrote {FIXTURE}")


if __name__ == "__main__":
    main()
