/**
 * The TypeScript hex math must agree with the Python it was ported from, case for case.
 *
 * The fixture is generated by `scripts/gen_hex_fixture.py` and guarded on the Python
 * side by `tests/test_hex_conformance.py`, so neither implementation can drift without
 * one of the two suites failing.
 */

import { describe, expect, it } from 'vitest';

import fixture from './fixtures/hex-conformance.json' with { type: 'json' };

import {
  astar,
  axialToOffset,
  axialToPixel,
  distance,
  hexRange,
  key,
  neighbors,
  offsetToAxial,
  pixelToAxial,
  ring,
  roundAxial,
  type Hex,
} from '../src/hex.js';

const pair = (h: Hex): [number, number] => [h.q, h.r];
const hex = ([q, r]: number[]): Hex => ({ q: q!, r: r! });

describe('neighbors', () => {
  it('matches the Python, including the direction ordering', () => {
    for (const c of fixture.neighbors) {
      expect(neighbors(hex(c.coord)).map(pair), `neighbors(${c.coord})`).toEqual(c.result);
    }
  });
});

describe('distance', () => {
  it('matches the Python for every pair', () => {
    for (const c of fixture.distance) {
      expect(distance(hex(c.a), hex(c.b)), `distance(${c.a}, ${c.b})`).toBe(c.result);
    }
  });
});

describe('ring', () => {
  it('matches the Python, including the walk order', () => {
    for (const c of fixture.ring) {
      expect(ring(hex(c.center), c.radius).map(pair), `ring(${c.center}, ${c.radius})`).toEqual(
        c.result,
      );
    }
  });
});

describe('hexRange', () => {
  it('matches the Python', () => {
    for (const c of fixture.hexRange) {
      expect(
        hexRange(hex(c.center), c.radius).map(pair),
        `hexRange(${c.center}, ${c.radius})`,
      ).toEqual(c.result);
    }
  });
});

describe('axialToPixel', () => {
  it('matches the Python to floating-point tolerance', () => {
    for (const c of fixture.axialToPixel) {
      const { x, y } = axialToPixel(hex(c.coord), fixture.hexSize);
      expect(x, `x of ${c.coord}`).toBeCloseTo(c.result[0]!, 10);
      expect(y, `y of ${c.coord}`).toBeCloseTo(c.result[1]!, 10);
    }
  });
});

describe('pixelToAxial', () => {
  it('matches the Python', () => {
    for (const c of fixture.pixelToAxial) {
      expect(pair(pixelToAxial(c.x, c.y, fixture.hexSize)), `(${c.x}, ${c.y})`).toEqual(c.result);
    }
  });
});

describe('roundAxial', () => {
  it('matches the Python, half-to-even included', () => {
    for (const c of fixture.roundAxial) {
      expect(pair(roundAxial(c.q, c.r)), `roundAxial(${c.q}, ${c.r})`).toEqual(c.result);
    }
  });

  it('rounds half to even rather than half up', () => {
    // Guarding the guard: if this port ever reverts to Math.round, the fixture cases
    // above would catch it, but this states the actual rule so the failure reads clearly.
    expect(pair(roundAxial(0.5, 0.5))).toEqual([0, 1]);
    expect(pair(roundAxial(-0.5, -0.5))).toEqual([0, -1]);
  });
});

describe('offset layout conversions', () => {
  it('offsetToAxial matches the Python for odd and even columns', () => {
    for (const c of fixture.offsetToAxial) {
      expect(pair(offsetToAxial(c.col, c.row)), `offsetToAxial(${c.col}, ${c.row})`).toEqual(
        c.result,
      );
    }
  });

  it('axialToOffset matches the Python', () => {
    for (const c of fixture.axialToOffset) {
      const { col, row } = axialToOffset(hex(c.coord));
      expect([col, row], `axialToOffset(${c.coord})`).toEqual(c.result);
    }
  });

  it('round-trips', () => {
    for (const c of fixture.axialToOffset) {
      const h = hex(c.coord);
      const { col, row } = axialToOffset(h);
      expect(pair(offsetToAxial(col, row))).toEqual(pair(h));
    }
  });
});

describe('astar', () => {
  const { width, height, blockedColumn, blockedRows, start, goal, path } = fixture.astar;

  /** The same cost formula `scripts/gen_hex_fixture.py` uses. */
  const cost = (q: number, r: number): number =>
    q === blockedColumn && blockedRows.includes(r) ? Infinity : 1 + ((q * 7 + r * 13) % 5);

  const grid = new Map<string, { cost: number }>();
  for (let q = 0; q < width; q++) {
    for (let r = 0; r < height; r++) grid.set(key({ q, r }), { cost: cost(q, r) });
  }

  it('finds the same path as the Python, tie-breaks included', () => {
    const found = astar(grid, hex(start), hex(goal), (n) => n.cost);
    expect(found).not.toBeNull();
    expect(found!.map(pair)).toEqual(path);
  });

  it('returns a connected path that avoids the obstacle', () => {
    const found = astar(grid, hex(start), hex(goal), (n) => n.cost)!;
    for (let i = 1; i < found.length; i++) {
      expect(distance(found[i - 1]!, found[i]!), `step ${i} is not a single hex`).toBe(1);
    }
    for (const step of found) {
      expect(Number.isFinite(cost(step.q, step.r)), `${key(step)} is impassable`).toBe(true);
    }
  });

  it('returns null when the goal is off the grid', () => {
    expect(astar(grid, hex(start), { q: 99, r: 99 }, (n) => n.cost)).toBeNull();
  });

  it('never routes through an edge the edge cost forbids', () => {
    // The Python checks the combined cost after adding the edge term precisely so an
    // impassable edge is skipped rather than pushed with an infinite score.
    const blockAll = (): number => Infinity;
    expect(astar(grid, hex(start), hex(goal), (n) => n.cost, blockAll)).toBeNull();
  });
});
